name: rl
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pytorch                                                                     
  - pytorch-cuda=12.1                                                           
  - cuda-toolkit         
  - pandas
  - pip
  - matplotlib
  - gymnasium[atari, accept-rom-licesnse]
  - pip:
    - Shimmy
    - ale-py
    - autorom[accept-rom-license]
